name: Weekly Ticket Schedule

on:
  schedule:
    - cron:  '0 15 * * *'  # 매일 KST 00:00 (== UTC 15:00)
  workflow_dispatch:

jobs:
  run-ticket-scraper:
    runs-on: ubuntu-22.04  # 더 안정적으로

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Weekly Ticket Scraper
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_ACT_DB_ID: ${{ secrets.NOTION_ACT_DB_ID }}
          ICAL_USERNAME: ${{ secrets.ICAL_USERNAME }}
          ICAL_TOKEN: ${{ secrets.ICAL_TOKEN }}
          ICAL_REPO: ${{ secrets.ICAL_REPO }}
          CHROME_BIN: /usr/bin/google-chrome  # ✅ 안정성 추가
          TZ: Asia/Seoul  # 타임존 설정
        run: python run.py
