name: Weekly Ticket Schedule

on:
  schedule:
    - cron:  '0 15 * * 0,3'  # 매주 일, 수요일 KST 00:00 (== UTC 15:00)
  workflow_dispatch:

jobs:
  run-ticket-scraper:
    runs-on: ubuntu-22.04

    permissions:
      contents: write


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Weekly Ticket Scraper
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_ACT_DB_ID: ${{ secrets.NOTION_ACT_DB_ID }}
          NOTION_TITLE_DB_ID: ${{ secrets.NOTION_TITLE_DB_ID }}
          GB_ICAL_URL : ${{ secrets.GB_ICAL_URL }}
          CHROME_BIN: /usr/bin/google-chrome
          TZ: Asia/Seoul
        run: python run.py

      - name: Prepare for pushing .ics files to main branch
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

          git fetch origin main
          git worktree add temp-main origin/main

          rm -rf temp-main/ical_exports
          mkdir -p temp-main/ical_exports
          cp -r ical_exports/*.ics temp-main/ical_exports/

      - name: Commit & Push .ics files to main
        run: |
          cd temp-main

          git add ical_exports/*.ics
          git diff --cached --quiet || git commit -m "Update .ics schedule files"
          git push origin HEAD:main

      - name: Cleanup
        run: |
          git worktree remove temp-main --force
